version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "helloWorldStack2022"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-176mpgdqai6ty"
s3_prefix = "helloWorldStack2022"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=471393700041.dkr.ecr.us-east-1.amazonaws.com/helloworldstack2022ebf1cd4d/helloworldfunction19d43fc4repo"]
